collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5989975
  brandStrength: 0.6011965812649578
  lightness: 0.2700501
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  rhythmicContrast: 0.7211779
typography_spectrum: 0.8922306
layout_spectrum: 0.2706767
name: craig b. photography
